language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t bartek26/react-test -f ./client/Dockerfile.dev ./client

  # ./client/Dockerfile.dev - We should provide the path, because the dockerfile won't be in the same folder as Dockerfile.dev
  # ./client - The folder in which the image is to be built


script:
  - docker run -e CI=true bartek26/react-test npm test

# After completed tests
after_success:
  - docker build -t bartek26/multi-client ./client
  - docker build -t bartek26/multi-nginx ./nginx
  - docker build -t bartek26/multi-server ./server
  - docker build -t bartek26/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -- password-stdin
  # Take  those images and push them to docker hub
  - docker push bartek26/multi-client
  - docker push bartek26/multi-nginx
  - docker push bartek26/multi-server
  - docker push bartek26/multi-worker
